config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  root :to => "home#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'loans_section/loans/dashboard#index', :constraints => lambda { |request| request.env['warden'].user.role == 'loan_officer' if request.env['warden'].user }, as: :loans_section_root
  root :to => 'consumers_section/store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'cashier' if request.env['warden'].user }, as: :cashier_root
  scope "/admin" do
    resources :users, only: [:show, :edit, :update]
    resources :settings, only: [:index], module: :admin
    resources :cooperatives, only: [:show, :new, :create], module: :admin do
      resources :departments, only: [:new, :create]
    end
  end
  resources :relationships, only: [:new, :create], module: :members
  resources :members, except: [:destroy] do
    resources :relationships, only: [:new, :create]
    resources :common_share_capitals, only: [:new, :create], module: :members
    resources :preferred_share_capitals, only: [:new, :create], module: :members
    resources :savings, only: [:new, :create], module: :members
    resources :time_deposits, only: [:new, :create], module: :members
    resources :loans, only: [:new, :create], module: :loans_section
    resources :membership_fees, only: [:new, :index], module: :fees
  end
  resources :users, only: [:index, :new, :create]
  get 'accounting/reports/balance_sheet' => 'accounting_/reports#balance_sheet'
  get 'accounting/reports/financial_statement' => 'accounting/reports#financial_statement'
  get 'accounting/reports/income_statement' => 'accounting/reports#income_statement'

  resources :coop_services, only: [:index]
  namespace :coop_services do
    resources :share_capital_products, only: [:new, :create]
    resources :savings_products, only: [:new, :create]
    resources :time_deposit_products, only: [:new, :create]

  end
  resources :time_deposits, only: [:index, :show] do
    resources :deposits, only: [:new, :create], module: :time_deposits
  end
  resources :savings, only: [:index, :show] do
    resources :deposits, only: [:new, :create], module: :savings
    resources :withdrawals, only: [:new, :create], module: :savings
  end
  resources :share_capitals, only: [:index, :show] do
    resources :capital_build_ups, only: [:new, :create], module: :share_capitals
  end
  namespace :coop do
    resources :settings, only: [:index]
    resources :programs, only: [:new, :create]
    resources :branches, only: [:show] do
      resources :departments, only: [:new, :create]
    end
    resources :departments, only: [:show]
    resources :cooperatives, only: [:edit, :update] do
      resources :branches, only: [:new, :create, :show]
    end
  end
  namespace :loans_section do
    resources :settings, only: [:index]
    resources :loan_products, only: [:new, :create], module: :settings
    resources :loan_approvers, only: [:new, :create], module: :settings

    resources :imbursements, only: [:index]
    resources :loans, only: [:index, :show] do
      resources :approvals, only: [:new, :create], module: :loans
      resources :disbursements, only: [:new, :create], module: :loans
      resources :payments, only: [:new, :create], module: :loans
    end
  end


  namespace :accounting do
    resources :balance_sheet, only:[:index]
    resources :income_statement, only:[:index]
    resources :dashboard, only: [:index]
    resources :reports, only:[:index]
    resources :accounts do
      get :autocomplete_accounting_account_name, on: :collection
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member
    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :member_entries, only: [:new, :create]
    resources :employee_entries, only: [:new, :create]
    resources :supplier_entries, only: [:new, :create]

    resources :entries do
      get :autocomplete_entry_description, on: :collection
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
    resources :reports, only:[:index]
    resources :financial_statement, module: :reports
    resources :statement_of_operations, only:[:index], module: :reports
  end

  resources :consumers_section, only: [:index]
  namespace :consumers_section do
    resources :store, only: [:index]
    resources :line_items, only: [:new, :create]
    resources :products, only: [:index, :new, :create, :show] do
      resources :stocks, only: [:new, :create], module: :products
    end
    resources :stocks, only: [:index, :show, :new, :create]
    resources :orders, only: [:index, :show, :new, :create]
  end

  resources :suppliers, only: [:index, :show, :new,:create]
end

app/models/accounting/amount.rb
module Accounting
  class Amount < ActiveRecord::Base
    belongs_to :entry, :class_name => 'Accounting::Entry'
    belongs_to :account, :class_name => 'Accounting::Account'

    validates_presence_of :type, :amount, :entry, :account
  end
end

app/models/accounting/amounts_extension.rb
module Accounting
  module AmountsExtension
    def balance(hash={})
      if hash[:from_date] && hash[:to_date]
        from_date = hash[:from_date].kind_of?(Date) ? hash[:from_date] : DateTime.parse(hash[:from_date].strftime('%Y/%m/%d'))
        to_date = hash[:to_date].kind_of?(Date) ? hash[:to_date] : DateTime.parse(hash[:to_date].strftime('%Y/%m/%d'))
        includes(:entry).where('entries.entry_date' => from_date..to_date).sum(:amount)
      else
        sum(:amount)
      end
    end

    # Returns a sum of the referenced Amount objects.
    #
    # This is used primarly in the validation step in Plutus::Entry
    # in order to ensure that the debit and credits are canceling out.
    #
    # Since this does not use the database for sumation, it may be used on non-persisted records.
    def balance_for_new_record
      balance = BigDecimal.new('0')
      each do |amount_record|
        if amount_record.amount
          balance += amount_record.amount
        else
          balance = nil
        end
      end
      return balance
    end
  end
end

app/models/accounting/asset.rb
module Accounting
  class Asset < Account

    def balance(options={})
      super(options)
    end

    def self.balance(options={})
      super(options)
    end
  end
end

app/models/accounting/credit_amount.rb
module Accounting
  class CreditAmount < Amount
  end
end

app/models/accounting/debit_amount.rb
module Accounting
  class DebitAmount < Amount
  end
end

app/models/accounting/equity.rb
module Accounting
  class Equity < Account
    self.normal_credit_balance = true

    def balance(options={})
      super
    end

    def self.balance(options={})
      super
    end
  end
end

app/models/accounting/expense.rb
module Accounting
  class Expense < Account

    self.normal_credit_balance = false

    def balance(options={})
      super
    end

    def self.balance(options={})
      super
    end
  end
end

app/models/accounting/liability.rb
module Accounting

  class Liability < Account

    self.normal_credit_balance = true

    def balance(options={})
      super
    end

    def self.balance(options={})
      super
    end
  end
end

app/models/accounting/revenue.rb
module Accounting
  class Revenue < Account

    self.normal_credit_balance = true

    def balance(options={})
      super
    end

    def self.balance(options={})
      super
    end
  end
end

app/controllers/accounting/accounting_controller.rb
class AccountingController < ApplicationController
  def index
  end
end 

app/controllers/accounting/accounts_controller.rb
module Accounting
  class AccountsController < ApplicationController
    before_action :set_account, only: [:show, :edit, :update, :destroy]
    before_action :set_type

    autocomplete :accounting_account, :name, full: true

    def index
      if params[:name].present?
        @accounts = type_class.search_by_name(params[:name])
      else
        @accounts = type_class.all.order(:code)
      end
      # authorize @accounts
    end

    def show
    end

    def new
      @account = type_class.new
    end

    def edit
    end

    def create
      @accounts = Accounting::Account.all.order(:type)
      @account = Accounting::Account.create(account_params)
    end

    def update
      @accounts = Accounting::Account.all
      @account = Accounting::Account.find(params[:id])
      @account.update_attributes(account_params)
    end

    def activate
      @account = Accounting::Account.find(params[:id])
      @account.active!
      redirect_to accounting_index_url
    end
    def deactivate
      @account = Accounting::Account.find(params[:id])
      @account.inactive!
      redirect_to accounting_index_url
    end

    def destroy
      @account.destroy
      redirect_to accounts_url
    end

    private

    def set_type
      @type = type
    end

    def type
      Accounting::Account.types.include?(params[:type]) ? params[:type] : "Accounting::Account"
    end

    def type_class
      type.constantize
    end

    def set_account
      @account = type_class.find(params[:id])
    end

    def account_params
      params.require(type.underscore.gsub('/', '_').to_sym).permit(:name, :type, :code)
    end

  end
end

app/controllers/accounting/balance_sheet_controller.rb
class Accounting::BalanceSheetController < ApplicationController
  def index
    first_entry = Accounting::Entry.order('date ASC').first
    @from_date = first_entry ? first_entry.date: Date.today
    @to_date = params[:date] ? Date.parse(params[:date]) : Date.today
    @assets = Accounting::Asset.all
    @liabilities = Accounting::Liability.all
    @equity = Accounting::Equity.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/accounting/credit_payments_controller.rb
module Accounting
  class CreditPaymentsController < ApplicationController

    def new
      @line_item = LineItem.find(params[:line_item_id])
      @entry = Accounting::Entry.new
      authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @line_item = LineItem.find(params[:line_item_id])
      @entry = Accounting::Entry.create(entry_params)
      @entry.commercial_document = @line_item.order
      @entry.recorder = current_user
      if @entry.save
        @line_item.cash!
        redirect_to @line_item.stock.product, notice: "Payment saved successfully."
      else
        render :new
      end
      authorize @entry
    end

    def show
      @entry = Accounting::Entry.find(params[:id])
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:date, :description, :reference_number, debit_amounts_attributes:[:amount, :account], credit_amounts_attributes:[:amount, :account])
    end
  end
end

app/controllers/accounting/dashboard_controller.rb
module Accounting
  class DashboardController < ApplicationController
    def index
      authorize [:accounting, :dashboard]
    end
  end
end

app/controllers/accounting/employee_entries_controller.rb
module Accounting 
  class EmployeeEntriesController < ApplicationController 
    def new
      @entry = Accounting::Entry.new
      authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @entry = Accounting::Entry.create(entry_params)
      @entry.recorder = current_user
      if @entry.save
        redirect_to accounting_entries_path, notice: 'Entry has been saved successfully.'
      else
        render :new
      end
      authorize @entry
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:commercial_document_id, :commercial_document_type, :date, :description, :reference_number, debit_amounts_attributes:[:amount, :account], credit_amounts_attributes:[:amount, :account])
    end
  end 
end

app/controllers/accounting/entries_controller.rb
module Accounting
  class EntriesController < ApplicationController

    autocomplete :entry, :description, full: true, class_name: 'Accounting::Entry'

    def index
      if params[:description].present?
      @entries = Accounting::Entry.search_by_name(params[:description]).order(:entry_date).page(params[:page]).per(30)

      else
        @entries = Accounting::Entry.includes(:commercial_document).all.order('entry_date DESC').page(params[:page]).per(30)
        @from_date = params[:from_date] ? Time.parse(params[:from_date]) : Time.now.beginning_of_day
        @to_date = params[:to_date] ? Time.parse(params[:to_date]) : Time.now.end_of_day
        respond_to do |format|
          format.html
          format.pdf do
            pdf = EntriesPdf.new(@entries, @from_date, @to_date, view_context)
              send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Entries Report.pdf"
          end
        end
      end
      # authorize @entries
    end

    def new
      @entry = Accounting::Entry.new
      # authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @entries = Accounting::Entry.all
      @entry = Accounting::Entry.create(entry_params)
      @entry.recorder = current_user
      if @entry.save
        redirect_to accounting_entries_path, notice: 'Entry has been saved successfully.'
      else
        render :new
      end
      authorize @entry
    end

    def show
      @entry = Accounting::Entry.find(params[:id])
    end

    def autocomplete
      @entries = Accounting::Entry.all
      @names = @entries.select('description').map(&:description)
      render json: @names
    end

    def scope_to_date
      @entries = Accounting::Entry.created_between(params[:from_date], params[:to_date])
      @from_date = params[:from_date] ? Time.parse(params[:from_date]) : Time.now.beginning_of_day
      @to_date = params[:to_date] ? Time.parse(params[:to_date]) : Time.now.end_of_day
      respond_to do |format|
        format.html
        format.pdf do
          pdf = EntriesPdf.new(@entries, @from_date, @to_date, view_context)
            send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Entries Report.pdf"
        end
      end
    end

    def destroy
      @entry = Accounting::Entry.find(params[:id])
      @entry.destroy
      redirect_to accounting_entries_path, alert: 'Entry has been deleted.'
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:date, :description, :reference_number, debit_amounts_attributes:[:amount, :account], credit_amounts_attributes:[:amount, :account])
    end
  end
end

app/controllers/accounting/income_statement_controller.rb
class Accounting::IncomeStatementController < ApplicationController
  def index
    @from_date = params[:from_date] ? Date.parse(params[:from_date]) : Date.today.at_beginning_of_month
    @to_date = params[:to_date] ? Date.parse(params[:to_date]) : Date.today
    @revenues = Accounting::Revenue.all
    @expenses = Accounting::Expense.all

    respond_to do |format|
      format.html # index.html.erb
      format.pdf do
        pdf = Accounting::IncomeStatementPdf.new(@revenues, @expenses,  @from_date, @to_date, view_context)
        send_data pdf.render, type: "application/pdf", disposition: 'inline', file_name: "Income Statement.pdf"
      end
    end
  end
end

app/controllers/accounting/member_entries_controller.rb
module Accounting 
  class MemberEntriesController < ApplicationController 
    def new
      @entry = Accounting::Entry.new
      authorize @entry
      @entry.debit_amounts.build
      @entry.credit_amounts.build
    end

    def create
      @entry = Accounting::Entry.create(entry_params)
      @entry.recorder = current_user
      if @entry.save
        redirect_to accounting_entries_path, notice: 'Entry has been saved successfully.'
      else
        render :new
      end
      authorize @entry
    end

    private
    def entry_params
      params.require(:accounting_entry).permit(:commercial_document_id, :commercial_document_type, :date, :description, :reference_number, debit_amounts_attributes:[:amount, :account], credit_amounts_attributes:[:amount, :account])
    end
  end 
end

app/views/accounting/entries/index.html.erb
<div id="entryModal" class="modal fade"></div>
<div class="row">
  <div class="col-md-12">
  	<div class="box box-solid">
    	<div class="box-body">
				<div class="col-md-4">
			  	<ul class="nav navbar-nav">
			      <li class="dropdown">
			        <button href="#" class="dropdown-toggle btn btn-primary" data-toggle="dropdown" aria-expanded="false">Show Activity <b class="caret"></b></button>
			        <ul class="dropdown-menu dropdown-menu-right">
			          <li><%=link_to 'This Day', scope_to_date_accounting_entries_path(:from_date => Time.zone.now.beginning_of_day, :to_date => Time.zone.now.end_of_day, format: 'pdf') %></li>
						    <li> <%=link_to 'This Week', scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_week, to_date: Time.zone.now.end_of_week, format: 'pdf') %></li>
						    <li> <%=link_to 'This Month', scope_to_date_accounting_entries_path(from_date: Time.zone.now.beginning_of_month, to_date: Time.zone.now.end_of_month, format: 'pdf') %></li>
			        </ul>
			      </li>
			    </ul>
				</div>
				<div class="col-md-4">
			    <%=form_tag accounting_entries_path, method: :get do %>
			      <div class="input-group stylish-input-group" id="entry-prefetch">
			        <%= autocomplete_field_tag "description", params[:description], autocomplete_entry_description_accounting_entries_path, class: 'form-control', placeholder: 'Search Entry...' %>
			        <span class="input-group-btn">
			          <%= button_tag(type: 'submit', class: "btn btn-flat") do %>
			            <i class="fa fa-search"></i>
			          <% end %>
			        </span>
			      </div>
			    <% end %>
				</div>
				<div class="col-md-4">
				<ul class="nav navbar-nav pull-right">
			      <li class="dropdown">
			        <button href="#" class="dropdown-toggle btn btn-danger" data-toggle="dropdown" aria-expanded="false">New Entry <b class="caret"></b></button>
			        <ul class="dropdown-menu dropdown-menu-right">
			          <li><%=link_to 'New Entry', new_accounting_entry_path %></li>
						    <li> <%=link_to 'New Entry (Member)', new_accounting_member_entry_path%></li>
						    <li> <%=link_to 'New Entry (Employee)', new_accounting_employee_entry_path %></li>
						    <li> <%=link_to 'New Entry (Supplier)', new_accounting_supplier_entry_path %></li>

			        </ul>
			      </li>
			    </ul>
				</div>
			</div>
			<hr>
			<div class="row">
			  <div class="col-md-3">
			    <span class="pull-right title">Filter Date:</span>
			  </div>
			  <div class="col-md-9">
			    <%= form_tag({:action => 'index'}, {:method => :get})  do %>
			      <div class="row">
			        <div class="col-md-4">
			          <%= text_field_tag :from_date, @from_date, :class => 'datepicker form-control'%>
			        </div>
			        <div class="col-md-4">
			          <%= text_field_tag :to_date, @to_date, :class => 'form-control datepicker'%>
			        </div>
			        <div class="col-md-4">
			        	<button type="submit" class="btn btn-success active"> Go </button>
			          <%=link_to "PDF", accounting_entries_path(format: 'pdf', from_date: @from_date, to_date: @to_date), class: "btn btn-default active"%>
			        </div>
			      </div>
			    <% end %>
			  </div>
			</div>
			<br>
			<div class="row">
				<div class="col-md-12">
				  <div class="card">
				    <div class="header">
				    </div>
						<div class="content">
							<div class="table table-responsive">
								<table class="table table-striped">
									<thead>
										<tr class="title">
			                <th> Date </th>
											<th> Description </th>
			                <th> Member / Supplier / Employee </th>
											<th> Employee </th>
											<th> Debit</th>
											<th> Credit </th>
										</tr>
									</thead>
									<tbody class="entry-index">
										<%=render 'index' %>
									</tbody>
								</table>
								<div class="modal-footer">
				          <center><%= paginate @entries, :window => 1 %></center>
				        </div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/accounting/entries/new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= simple_form_for @entry, html: { style: "display:inline;" } do |f| %>
      <div class="modal-header">
        <h3 class="modal-title">New Entry</h3>
      </div>
      <div class="modal-body">
        <ul class="errors text-danger">
        </ul>
        <div class="row">
          <div class="col-md-6">
            <%=f.input :date, as: :string, input_html: { class: "datepicker" } %>
          </div>
          <div class="col-md-6">
            <%=f.input :reference_number %>
          </div>
        </div>
        <%=f.input :description %>

        <%=f.simple_fields_for :debit_amounts do |ff| %>
          <%=ff.input :amount %>
          <%=ff.input :account, collection: Accounting::Account.active.all.pluck(:name), label: 'Debit Account' %>
        <% end %>
        <%=f.simple_fields_for :credit_amounts do |ff| %>
          <%=ff.input :amount, as: :hidden %>
          <%=ff.input :account, collection: Accounting::Account.active.all.pluck(:name), label: 'Credit Account' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", accounting_entries_path, class: "btn pull-left", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  $("#accounting_entry_debit_amounts_attributes_0_account").select2({
    theme: "bootstrap",
    placeholder: 'Select Account',
    width: '100%',
    dropdownAutoWidth : true
  });
  $("#accounting_entry_credit_amounts_attributes_0_account").select2({
    theme: "bootstrap",
    placeholder: 'Select Account',
    width: '100%',
    dropdownAutoWidth : true
  });
</script>

app/views/accounting/entries/new.js.erb
$("#entryModal").html("<%= escape_javascript(render 'new') %>")
$('#entryModal').modal({backdrop: 'static', keyboard: false, show: true})
$('.datepicker').datepicker({
	format: "yyyy/mm/dd/",
	orientation: "auto bottom",
	todayHighlight: 'true',
	autoclose: 'true'
	});
$("#accounting_entry_debit_amounts_attributes_0_account").select2({
  theme: "bootstrap",
  placeholder: 'Select Account',
  width: '100%',
  dropdownAutoWidth : true
});
$("#accounting_entry_credit_amounts_attributes_0_account").select2({
  theme: "bootstrap",
  placeholder: 'Select Account',
  width: '100%',
  dropdownAutoWidth : true
});

app/views/accounting/entries/show.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="box box-solid">
			<div class="box-header">
				<h4>Entry Details</h4>
					<div class="pull-right">
				  	<ul class="nav navbar-nav">
				      <li class="dropdown">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> <i class="fa fa-cog"></i></a>
				        <ul class="dropdown-menu dropdown-menu-right">
				          <li><%=link_to 'Delete', accounting_entry_path(@entry), method: :delete, data: {confirm: 'Are you sure you want to DELETE this entry? THIS ACTION CANNOT BE UNDONE.'} %></li>
				        </ul>
				      </li>
				    </ul>
				  </div>
				</h4>
			</div>
			<div class="box-body">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<p><strong>Date</strong></p>
						<span>&nbsp &nbsp &nbsp<%=@entry.date.strftime("%B %e, %Y") %></span>
						<hr>
						<p><strong>Description</strong></p>
						<span>&nbsp &nbsp &nbsp<%=@entry.description %></span><br>
						<hr>
						<p><strong>Member/Employee/Supplier:</strong></p>
						<span>&nbsp &nbsp &nbsp<%=@entry.commercial_document.try(:full_name) %></span><br>
						<hr>
						<p><strong>Reference Number</strong></p>
						<span>&nbsp &nbsp &nbsp<%=@entry.reference_number%></span>
						<hr>
						<p><strong>Debited Account(s)</strong></p>
						<%@entry.debit_amounts.each do |d|%>
							<div class="row">
								<div class="col-md-12">
									&nbsp &nbsp &nbsp<%=d.account.name %><span class="pull-right"><%=number_to_currency d.amount %></span>
								</div>
							</div>
						<%end %>
						<hr>

						<p><strong>Credited Account(s)</strong></p>
						<%@entry.credit_amounts.each do |d|%>
							<div class="row">
								<div class="col-md-12">
									&nbsp &nbsp &nbsp<%=d.account.name %> <span class="pull-right"><%=number_to_currency d.amount %></span>
								</div>
							</div>
						<% end %>
						<br>
						<div class="modal-footer">
							<%= link_to "Back", accounting_entries_path, class: 'btn btn-default pull-left' %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="entryModal" class="modal fade"></div>