config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  devise_for :users, :controllers => { :registrations => "users", sessions: "users/sessions" }
  root :to => "home#index", :constraints => lambda { |request| request.env['warden'].user.nil? }, as: :unauthenticated_root
  root :to => 'loans_section/loans/dashboard#index', :constraints => lambda { |request| request.env['warden'].user.role == 'loan_officer' if request.env['warden'].user }, as: :loans_section_root
  root :to => 'consumers_section/store#index', :constraints => lambda { |request| request.env['warden'].user.role == 'cashier' if request.env['warden'].user }, as: :cashier_root
  scope "/admin" do
    resources :users, only: [:show, :edit, :update]
    resources :settings, only: [:index], module: :admin
    resources :cooperatives, only: [:show, :new, :create], module: :admin do
      resources :departments, only: [:new, :create]
    end
  end
  resources :relationships, only: [:new, :create], module: :members
  resources :members, except: [:destroy] do
    resources :relationships, only: [:new, :create]
    resources :common_share_capitals, only: [:new, :create], module: :members
    resources :preferred_share_capitals, only: [:new, :create], module: :members
    resources :savings, only: [:new, :create], module: :members
    resources :time_deposits, only: [:new, :create], module: :members
    resources :loans, only: [:new, :create], module: :loans_section
    resources :membership_fees, only: [:new, :index], module: :fees
  end
  resources :users, only: [:index, :new, :create]
  get 'accounting/reports/balance_sheet' => 'accounting_/reports#balance_sheet'
  get 'accounting/reports/financial_statement' => 'accounting/reports#financial_statement'
  get 'accounting/reports/income_statement' => 'accounting/reports#income_statement'

  resources :coop_services, only: [:index]
  namespace :coop_services do
    resources :share_capital_products, only: [:new, :create]
    resources :savings_products, only: [:new, :create]
    resources :time_deposit_products, only: [:new, :create]

  end
  resources :time_deposits, only: [:index, :show] do
    resources :deposits, only: [:new, :create], module: :time_deposits
  end
  resources :savings, only: [:index, :show] do
    resources :deposits, only: [:new, :create], module: :savings
    resources :withdrawals, only: [:new, :create], module: :savings
  end
  resources :share_capitals, only: [:index, :show] do
    resources :capital_build_ups, only: [:new, :create], module: :share_capitals
  end
  namespace :coop do
    resources :settings, only: [:index]
    resources :programs, only: [:new, :create]
    resources :branches, only: [:show] do
      resources :departments, only: [:new, :create]
    end
    resources :departments, only: [:show]
    resources :cooperatives, only: [:edit, :update] do
      resources :branches, only: [:new, :create, :show]
    end
  end
  namespace :loans_section do
    resources :settings, only: [:index]
    resources :loan_products, only: [:new, :create], module: :settings
    resources :loan_approvers, only: [:new, :create], module: :settings

    resources :imbursements, only: [:index]
    resources :loans, only: [:index, :show] do
      resources :approvals, only: [:new, :create], module: :loans
      resources :disbursements, only: [:new, :create], module: :loans
      resources :payments, only: [:new, :create], module: :loans
    end
  end


  namespace :accounting do
    resources :balance_sheet, only:[:index]
    resources :income_statement, only:[:index]
    resources :dashboard, only: [:index]
    resources :reports, only:[:index]
    resources :accounts do
      get :autocomplete_accounting_account_name, on: :collection
      match "/activate" => "accounts#activate", via: [:post], on: :member
      match "/deactivate" => "accounts#deactivate", via: [:post], on: :member
    end
    resources :assets, controller: 'accounts', type: 'Accounting::Asset'
    resources :liabilities, controller: 'accounts', type: 'Accounting::Liability'
    resources :equities, controller: 'accounts', type: 'Accounting::Equity'
    resources :revenues, controller: 'accounts', type: 'Accounting::Revenue'
    resources :expenses, controller: 'accounts', type: 'Accounting::Expense'
    resources :member_entries, only: [:new, :create]
    resources :employee_entries, only: [:new, :create]
    resources :supplier_entries, only: [:new, :create]

    resources :entries do
      get :autocomplete_entry_description, on: :collection
      match "/scope_to_date" => "entries#scope_to_date", as: :scope_to_date, via: [:get], on: :collection
    end
    resources :reports, only:[:index]
    resources :financial_statement, module: :reports
    resources :statement_of_operations, only:[:index], module: :reports
  end

  resources :consumers_section, only: [:index]
  namespace :consumers_section do
    resources :store, only: [:index]
    resources :line_items, only: [:new, :create]
    resources :products, only: [:index, :new, :create, :show] do
      resources :stocks, only: [:new, :create], module: :products
    end
    resources :stocks, only: [:index, :show, :new, :create]
    resources :orders, only: [:index, :show, :new, :create]
  end

  resources :suppliers, only: [:index, :show, :new,:create]
end

app/models/member.rb
class Member < ApplicationRecord
  include PublicActivity::Common
  include PgSearch
  extend FriendlyId
  friendly_id :full_name, use: :slugged

  multisearchable :against => [:name],
                             :order_within_rank => "members.created_at DESC"

                             has_attached_file :avatar,
                                               styles: { large: "120x120>",
                                                         medium: "70x70>",
                                                         thumb: "40x40>",
                                                         small: "30x30>",
                                                         x_small: "20x20>"},
                                               default_url: ":style/default_product.jpg",
                                               :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
                                               :url => "/system/:attachment/:id/:style/:filename"

                             validates_attachment :avatar,
                                                content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  has_one :membership_fee, class_name: "Fees::MembershipFee", as: :feeable
  has_many :orders, class_name: "ConsumersSection::Order"
  has_many :line_items, through: :orders, class_name: "ConsumersSection::LineItem"
  has_many :share_capitals, class_name: "Members::ShareCapital"
  has_one :common_share_capital, class_name: "ShareCapitals::Common"
  has_one :preferred_share_capital, class_name: "ShareCapitals::Preferred"
  belongs_to :branch, class_name: 'Coop::Branch'
  has_many :occupations, class_name: "Members::Occupation"
  has_many :loans, class_name: "LoansSection::Loan"
  has_one :latest_loan, -> { order('created_at desc') }, class_name: 'LoansSection::Loan'
  has_many :savings, class_name: "Members::Saving"
  has_many :time_deposits, class_name: "Members::TimeDeposit"
  has_many :active_relationships, class_name: "Members::Relationship", foreign_key: 'relationer_id'
  has_many :passive_relationships, class_name: "Members::Relationship", foreign_key: 'relationee_id'
  has_many :relations, through: :active_relationships, source: :relationee
  has_many :relationers, through: :passive_relationships, source: :relationer
  has_many :contributions, class_name: "Members::Contribution"
  has_many :subscriptions, class_name: "Members::Subscription"



  validates :first_name, :middle_name, :last_name, :contact_number,
                 :date_of_birth, :civil_status, :sex, presence: true
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :contact_number, length:{minimum: 11, maximum: 12}


  enum sex:[:male, :female]
  enum civil_status:[:married, :single, :widower, :annulled]

   accepts_nested_attributes_for :occupations
  delegate :account_number, :balance, to: :common_share_capital, prefix: true, allow_nil: true
  delegate :account_number, :balance, to: :preferred_share_capital, prefix: true, allow_nil: true

  after_commit :create_subscriptions
  def self.possible_relationship(member)
    all.select{ |a| a.last_name == member.last_name }
  end
  def relationship(member)
    relationships.count
  end
  def active_relation(relation)
    relation = active_relationships.where(:relationee => relation).first
    relation.present?
    relation.try(:relationship_type)
  end
  def passive_relation(relation)
    relation = passive_relationships.where(:relationer => relation).first
    relation.present?
    relation.try(:relationship_type)
  end
  def name
    full_name
  end

  def full_name
    "#{self.first_name.try(:titleize)} #{self.middle_name.try(:first).try(:capitalize)}. #{self.last_name.try(:titleize)}"
  end

  def address
    "#{self.address_sitio.titleize}, #{self.address_barangay.titleize}, #{self.address_municipality.titleize}, #{self.address_province.titleize}"
  end

  def current_occupation
    Members::Occupation.current(self)
  end


  def first_and_last_name
    "#{first_name.try(:titleize)} #{last_name.try(:titleize)}"
  end

  private
  def create_subscriptions
    Coop::Program.default.all.each do |program|
      subscriptions.create(program: program, subscriber: self)
    end
  end
end

app/models/members/contribution.rb
module Members
  class Contribution < ApplicationRecord
    belongs_to :contributor, class_name: "Member", foreign_key: "member_id"
    belongs_to :subscription, class_name: "Members::Susbscription"
    belongs_to :entry, class_name: "Accounting::Entry"
  end
end

app/models/members/occupation.rb
module Members
  class Occupation < ApplicationRecord
    belongs_to :member
    validates :title, presence: true

    def self.current(member)
      all.where(current: true, member: member).last
    end
  end
end

app/models/members/relationship.rb
module Members
  class Relationship < ApplicationRecord
    belongs_to :relationer, class_name: "Member", foreign_key: 'relationer_id'
    belongs_to :relationee, class_name: "Member", foreign_key: 'relationee_id'

    enum relationship_type: [:mother, :father, :brother, :sister, :daughter, :son, :grandfather, :grandmother, :wife, :husband]

    validates :relationer_id, presence: true
    validates :relationee_id, presence: true 

  end
end

app/models/members/saving.rb
module Members
  class Saving < ApplicationRecord
    belongs_to :member
    belongs_to :branch, class_name: "Coop::Branch"
    belongs_to :savings_product, class_name: "CoopServices::SavingsProduct"

    validates :date_opened, presence: true
    validates :account_number, presence: true, uniqueness: true
    validates :savings_product_id, uniqueness: { scope: :member_id }

    delegate :name, to: :savings_product, prefix: true
    def balance
      deposits - withdrawals
    end
    def deposits
      Accounting::Account.find_by_name("Savings Deposits").credit_entries.where(:commercial_document => self).distinct.map{|a| a.credit_amounts.pluck(:amount).sum}.sum
    end
    def withdrawals
      Accounting::Account.find_by_name("Savings Deposits").debit_entries.where(:commercial_document => self).distinct.map{|a| a.debit_amounts.pluck(:amount).sum}.sum
    end
  end
end

app/models/members/share_capital.rb
module Members
  class ShareCapital < ApplicationRecord
    belongs_to :member
    belongs_to :branch, class_name: "Coop::Branch"
    validates :account_number, presence: true, uniqueness: true

    def balance
      capital_build_ups
    end
    def capital_build_ups
      Accounting::Account.find_by_name("Paid-up Share Capital - Common").credit_entries.where(:commercial_document => self).distinct.map{|a| a.credit_amounts.pluck(:amount).sum}.sum
    end
  end
end

app/models/members/subscription.rb
module Members
  class Subscription < ApplicationRecord
    belongs_to :member
    belongs_to :program, class_name: "Coop::Program"
  end
end

app/models/members/time_deposit.rb
module Members
  class TimeDeposit < ApplicationRecord
    belongs_to :member
    belongs_to :branch, class_name: "Coop::Branch"
    belongs_to :time_deposit_product, class_name: "CoopServices::TimeDepositProduct"


    has_many :deposits, as: :commercial_document, class_name: "Accounting::Entry"

    validates :account_number, presence: true, uniqueness: true
    validates :time_deposit_product_id, presence: true, uniqueness: { scope: :member }

    delegate :name, to: :time_deposit_product, prefix: true, allow_nil: true

    def balance
      deposits.map{|a| a.debit_amounts.pluck(:amount).sum}.sum
    end
  end
end

app/controllers/consumers_section/members_controller.rb
module ConsumersSection
  class MembersController < ApplicationController
    def index
      @members = Member.all
    end
    def show
      @member = Member.find(params[:id])
    end
  end
end

app/controllers/members/common_share_capitals_controller.rb
module Members
  class CommonShareCapitalsController < ApplicationController
    def new
      @member = Member.find(params[:member_id])
      @share_capital = @member.build_common_share_capital
    end
    def create
      @member = Member.find(params[:member_id])
      @share_capital = @member.create_common_share_capital(share_capital_params)
      @share_capital.branch = current_user.branch
      if @share_capital.save
        redirect_to @member, notice: "Common Share Capital Account subscribed successfully."
      else
        render :new
      end
    end

    private
    def share_capital_params
      params.require(:share_capitals_common).permit(:account_number)
    end
  end
end

app/controllers/members/preferred_share_capitals_controller.rb
module Members
  class PreferredShareCapitalsController < ApplicationController
    def new
      @member = Member.find(params[:member_id])
      @share_capital = @member.build_preferred_share_capital
    end
    def create
      @member = Member.find(params[:member_id])
      @share_capital = @member.create_preferred_share_capital(preferred_share_capital_params)
      @share_capital.branch = current_user.branch
      if @share_capital.save
        redirect_to @member, notice: "Share Capital Account saved successfully."
      else
        render :new
      end
    end

    private
    def preferred_share_capital_params
      params.require(:share_capitals_preferred).permit(:account_number)
    end
  end
end

app/controllers/members/relationships_controller.rb
module Members
  class RelationshipsController < ApplicationController
    def create
      @relation = Members::Relationship.create(relation_params)
      if @relation.save!
        redirect_to @relation.relationer, notice: "Relationship saved successfully"
      else
        render :new
      end
    end

    private
    def relation_params
      params.require(:members_relationship).permit(:relationer_id, :relationee_id, :relationship_type)
    end
  end
end

app/controllers/members/savings_controller.rb
module Members
  class SavingsController < ApplicationController
    def new
      @member = Member.find(params[:member_id])
      @saving = @member.savings.build
    end
    def create
      @member = Member.find(params[:member_id])
      @saving = @member.savings.create(saving_params)
      @saving.branch = current_user.branch
      if @saving.save
        redirect_to @member, notice: "Savings Account opened successfully."
      else
        render :new
      end
    end

    private
    def saving_params
      params.require(:members_saving).permit(:savings_product_id, :date_opened, :account_number)
    end
  end
end

app/controllers/members/time_deposits_controller.rb
module Members
  class TimeDepositsController < ApplicationController
    def new
      @member = Member.find(params[:member_id])
      @time_deposit = @member.time_deposits.build
    end
    def create
      @member = Member.find(params[:member_id])
      @time_deposit = @member.time_deposits.create(time_deposit_params)
      @time_deposit.branch = current_user.branch
      if @time_deposit.save
        redirect_to @member, notice: "Time Deposit Account opened successfully."
      else
        render :new
      end
    end

    private
    def time_deposit_params
      params.require(:members_time_deposit).permit(:time_deposit_product_id, :date_opened, :account_number)
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = current_branch.members.all
  end
  def new
    @member = Member.new
    authorize @member
  end
  def create
    @member = Member.create(member_params)
    @member.branch = current_user.branch
    if @member.save
      redirect_to @member, notice: "Member saved successfully."
    else
      render :new
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    @member.update(member_params)
    if @member.save
      redirect_to @member, notice: "updated successfully."
    else
      render :edit
    end
  end

  def show
    @member = Member.friendly.find(params[:id])
    @relationship = @member.active_relationships.build
  end

  private
  def member_params
    params.require(:member).permit(:first_name, :middle_name, :last_name, :sex, :date_of_birth, :contact_number, :civil_status, :avatar)
  end
end

app/views/members/partials/_loans.html.erb
<div class="tab-pane" id="loans">
  <%= link_to "New Loan", new_member_loan_path(@member), class: "btn btn-primary btn-flat" %>
  <hr />
  <% @member.loans.each do |loan| %>
    <div class="row">
      <div class="col-md-3">
        <%= link_to loan.loan_product_name, loans_section_loan_path(loan) %>
      </div>
      <div class="col-md-3">
        <%=number_to_currency loan.amount %>
      </div>
      <div class="col-md-3">
        <%=loan.application_date.strftime("%B %e, %Y") %>
      </div>
      <div class="col-md-3">

      </div>
    </div>
    <hr>
  <% end %>


</div>

app/views/members/partials/_overview.html.erb
<div class="active tab-pane" id="overview">
  Overview
  <%=link_to "New Relationship", new_relationship_path, class: "btn btn-primary" %>


<p class="text-muted"> Relationships </p>
<% if @member.active_relationships.present? %>
<% @member.relations.each do |relation| %>
  <div class="row">
    <div class="col-md-2">
      <%=image_tag(relation.avatar.url(:small), class: "img-circle", width: 35, height: 35) %>
    </div>
    <div class="col-md-4">
      <%=relation.full_name %>
    </div>
    <div class="col-md-2">
      <%=@member.active_relation(relation)%>
    </div>
  </div>
  <br>
  <% end %>
  <% end %>

  <% if @member.passive_relationships.present? %>
  <% @member.relationers.each do |relation| %>
    <div class="row">
      <div class="col-md-2">
        <%=image_tag(relation.avatar.url(:small), class: "img-circle", width: 35, height: 35) %>
      </div>
      <div class="col-md-4">
        <%=relation.full_name %>
      </div>
      <div class="col-md-2">
        <%=@member.passive_relation(relation)%>
      </div>
    </div>
    <br>
    <% end %>
    <% end %>
<hr>
  <% Member.possible_relationship(@member).each do |member| %>
    <div class="row">
      <div class="col-md-2">
        <%=image_tag(member.avatar.url(:small), class: "img-circle", width: 35, height: 35) %>
      </div>
      <div class="col-md-4">
        <%=member.full_name %>
      </div>
      <div class="col-md-2">
    <%=simple_form_for [@member, Members::Relationship.new], url: :relationships do |f| %>
      <%=f.input :relationer_id, input_html: { value: member.id }, as: :hidden  %>
      <%= f.input :relationee_id, input_html: { value: @member.id }, as: :hidden %>
      <%=f.input :relationship_type, collection: Members::Relationship.relationship_types.keys.to_a.map{ |a| [a.titleize, a] } %>
    </div>
    <div class="col-md-2">
      <%= f.submit "Add", class: "btn btn-primary btn-flat btn-sm" %>
    </div>
  </div>
    <% end %>
  <% end %>
  <h4 class="text-muted">Membership Details </h4>
  <p class="text-muted"> Membership Fee </p>
    <%=link_to "New Membership Fee", new_member_membership_fee_path(@member), class: "btn btn-primary btn-sm btn-flat" %>
</div>

app/views/members/partials/_purchases.html.erb
<div class="tab-pane" id="purchases">
  <p class="text-muted"> PURCHASES OVERVIEW </p>
  <div class="row">

      <div class="col-md-3">
        <small class="text-danger">
          CREDIT
        </small>
      </div>
      <div class="col-md-2">
        <small class="text-muted">
          PAYMENTS
        </small>
      </div>
      <div class="col-md-2">
        <small class="text-muted">
          BALANCE
        </small>
      </div>
    </div>
    <br>
    <hr>
    <p class="text-muted"> PURCHASES INSIGHTS </p>
    <div class="row">
      <div class="col-md-4">
    <small class="text-muted"> Products Mostly Purchased </small>
      1. Pampers 10 times
    </div>
    <div class="col-md-4">
        <small class="text-muted">
          TOTAL PURCHASE
        </small><br>
        <h3 class="text-muted"> <%=number_to_currency 899 %> </h3>

      </div>
    </div>
    <br>
    <hr>
    <p class="text-muted"> TRANSACTIONS HISTORY </p>
  <table class="table table-striped">
    <thead>
      <tr class="text-muted">
        <th>Date </th>
        <th> Reference No. </th>
        <th> Discount </th>
        <th> Total Cost </th>
        <th> Pay Type </th>
      </tr>
    </thead>
    <tbody>
      <% @member.orders.each do |order| %>
      <tr>
        <td><%= order.order_date.strftime("%b %e, %Y") %></td>
        <td><%= order.reference_number %></td>
        <td><%= number_to_currency order.total_discount %> </td>
        <td><%= number_to_currency order.total_cost %></td>
        <td> <span class="label label-<%=order.pay_type_color%>"><%= order.pay_type.try(:titleize) %></span></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/members/partials/_savings.html.erb
<div class="tab-pane" id="savings">
  <%=link_to "Open Savings", new_member_saving_path(@member), class: "btn btn-primary btn-flat" %>
  <hr />
  <% @member.savings.each do |savings| %>
    <div class="row">
      <div class="col-md-3">
        <%=savings.account_number %>
      </div>
      <div class="col-md-3">
        <%=savings.savings_product_name %>
      </div>
      <div class="col-md-3">
        <%= number_to_currency savings.balance %><br>
        <small> BALANCE </small>
      </div>
      <div class="col-md-3">
        <%=link_to "Deposit", new_saving_deposit_path(savings), class: "btn btn-default btn-sm btn-flat" %>
        <%=link_to "Withdraw", new_saving_withdrawal_path(savings), class: "btn btn-danger btn-sm btn-flat" %>

      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/members/partials/_settings.html.erb
<div class="tab-pane" id="settings">
  Settings
</div>

app/views/members/partials/_share_capital.html.erb
<div class="tab-pane" id="share-capital">
  <% if ShareCapitals::Common.for(@member).blank? %>
    <%=link_to "Subscribe (Common)", new_member_common_share_capital_path(@member), class: "btn btn-primary btn-flat" %>
  <% else %>
  <div class="row">
    <div class="col-md-3">
      <h4 class="text-muted"> Share Capital (Common) </h4>
      Account Number: <%= @member.common_share_capital_account_number %>
    </div>
    <div class="col-md-3">
      <%=number_to_currency @member.common_share_capital.balance %> <br>
      <small> BALANCE </small>
    </div>
    <div class="col-md-3">
      <%= link_to "New Capital Build Up", new_share_capital_capital_build_up_path(@member.common_share_capital), class: "btn btn-default btn-sm btn-flat" %>
    </div>
  </div>
  <% end %>
  <hr>
  <% if ShareCapitals::Preferred.for(@member).blank? %>
  <%=link_to "Subscribe (Preferred)", new_member_preferred_share_capital_path(@member), class: "btn btn-primary btn-flat" %>
  <% else %>
    <h4 class="text-muted"> Share Capital (Preferred) </h4>
    Account Number: <%= @member.preferred_share_capital_account_number %>
  <% end %>
</div>

app/views/members/partials/_time_deposits.html.erb
<div class="tab-pane" id="time-deposits">
  <h4 class="text-muted"> Time Deposits
  <span class="pull-right">
    <%=link_to "New Time Deposit", new_member_time_deposit_path(@member), class: "btn btn-primary btn-flat" %>
  </span>
    <hr>
</h4>

  <% @member.time_deposits.each do |time_deposit| %>
    <div class="row">
      <div class="col-md-3">
        <%=time_deposit.time_deposit_product_name %>
      </div>
      <div class="col-md-3">
        <%= time_deposit.account_number %>
      </div>
      <div class="col-md-3">
        <%= number_to_currency time_deposit.balance %><br>
        <small> BALANCE </small>
      </div>
      <div class="col-md-3">
        <%=link_to "Deposit", new_time_deposit_deposit_path(time_deposit), class: "btn btn-default btn-sm btn-flat" %>
      </div>
    </div>
    <br>
  <% end %>
</div>